name: Playwright Tests

on:
  push:
    branches: [ lesson22 ]
  pull_request:
    branches: [ lesson22 ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 1. Установка зависимостей Playwright тестов
      - name: Install dependencies
        run: npm ci
        working-directory: playwright-tests

      # 2. Установка недостающих типов TypeScript
      - name: Install TypeScript types
        run: npm install --save-dev @types/node @playwright/test
        working-directory: playwright-tests

      # 3. Установка браузеров Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
        working-directory: playwright-tests

      # 4. Запуск тестов
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: playwright-tests

      # 5. Сохранение отчета (если нужно)
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-tests/playwright-report/
          retention-days: 30